# Generated by Django 2.0 on 2020-02-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('no_of_part', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=20)),
                ('no_of_part', models.IntegerField()),
                ('place', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('Competition_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w_p', models.IntegerField()),
                ('position', models.IntegerField()),
                ('record', models.CharField(max_length=10)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Sportsman'),
        ),
    ]
