# Generated by Django 2.0 on 2020-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='no_of_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_of_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
