# Generated by Django 2.0 on 2020-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200224_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
