# Generated by Django 2.0 on 2020-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200310_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='record',
            field=models.TimeField(),
        ),
    ]
