# Generated by Django 2.0 on 2020-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200310_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='record',
            field=models.CharField(max_length=10),
        ),
    ]
