# Generated by Django 2.0 on 2020-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200310_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
