# Generated by Django 2.0 on 2020-03-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_competition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
