# Generated by Django 2.0 on 2020-03-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='date',
            new_name='date_year',
        ),
    ]
