# Generated by Django 2.0 on 2020-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200322_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='competition',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
