# Generated by Django 2.0 on 2020-03-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200322_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='w_p',
        ),
    ]
