# Generated by Django 2.0 on 2020-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_records_w_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
